use_frameworks!

target 'AKWeChatManager_Example' do
  pod 'AKWeChatManager', :path => '../'
  
  #pod 'AKWeChatSDK', :git => 'git@github.com:ArtisanKid/AKWeChatSDK.git'
  pod 'AKWeChatSDK', :path => '../../AKWeChatSDK'
  
  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      def installer.verify_no_static_framework_transitive_dependencies; end
  end

  target 'AKWeChatManager_Tests' do
    inherit! :search_paths

    
  end
end
